// Package main demonstrates multimodal tool outputs with v0.3.0 features.
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"

	agents "github.com/MitulShah1/openai-agents-go"
)

func main() {
	apiKey := os.Getenv("OPENAI_API_KEY")
	if apiKey == "" {
		log.Fatal("OPENAI_API_KEY environment variable is required")
	}

	client := openai.NewClient(option.WithAPIKey(apiKey))

	// Create an agent with multimodal tool capabilities
	agent := agents.NewAgent("multimodal_assistant")
	agent.Instructions = "You are a helpful assistant with access to tools that can return images and files."
	agent.Model = "gpt-4o-mini"

	// Tool 1: Generate placeholder image URL
	generateImageTool := agents.FunctionTool(
		"generate_placeholder_image",
		"Generates a placeholder image URL with specified dimensions",
		map[string]any{
			"type": "object",
			"properties": map[string]any{
				"width": map[string]any{
					"type":        "integer",
					"description": "Image width in pixels",
				},
				"height": map[string]any{
					"type":        "integer",
					"description": "Image height in pixels",
				},
				"text": map[string]any{
					"type":        "string",
					"description": "Text to display on the image",
				},
			},
			"required": []string{"width", "height"},
		},
		func(args map[string]any, _ agents.ContextVariables) (any, error) {
			width := int(args["width"].(float64))
			height := int(args["height"].(float64))
			text := ""
			if t, ok := args["text"].(string); ok {
				text = t
			}

			// Generate placeholder.com URL
			imageURL := fmt.Sprintf("https://via.placeholder.com/%dx%d", width, height)
			if text != "" {
				imageURL += fmt.Sprintf("?text=%s", text)
			}

			// Return as ImageContent with high detail
			return agents.ImageContent(imageURL, "high"), nil
		},
	)

	// Tool 2: Create report file
	createReportTool := agents.FunctionTool(
		"create_report",
		"Creates a text report file",
		map[string]any{
			"type": "object",
			"properties": map[string]any{
				"title": map[string]any{
					"type":        "string",
					"description": "Report title",
				},
				"content": map[string]any{
					"type":        "string",
					"description": "Report content",
				},
			},
			"required": []string{"title", "content"},
		},
		func(args map[string]any, _ agents.ContextVariables) (any, error) {
			title := args["title"].(string)
			content := args["content"].(string)

			// Generate report content
			report := fmt.Sprintf("# %s\n\n%s\n\n---\nGenerated by AI Agent", title, content)

			// Return as FileContent
			return agents.FileContent(
				[]byte(report),
				"report.md",
				"text/markdown",
			), nil
		},
	)

	// Tool 3: Simple text response (backward compatibility)
	getWeatherTool := agents.FunctionTool(
		"get_weather",
		"Gets the current weather for a location",
		map[string]any{
			"type": "object",
			"properties": map[string]any{
				"location": map[string]any{
					"type":        "string",
					"description": "City name",
				},
			},
			"required": []string{"location"},
		},
		func(args map[string]any, _ agents.ContextVariables) (any, error) {
			location := args["location"].(string)
			// Traditional string return (still works!)
			return fmt.Sprintf("Weather in %s: Sunny, 72°F", location), nil
		},
	)

	agent.Tools = []agents.Tool{generateImageTool, createReportTool, getWeatherTool}

	// Create runner
	runner := agents.NewRunner(&client)

	// Example 1: Request an image
	fmt.Println("=== Example 1: Multimodal Image Output ===")
	messages1 := []openai.ChatCompletionMessageParamUnion{
		openai.UserMessage("Generate a 300x200 placeholder image with the text 'Hello v0.3.0'"),
	}

	result, err := runner.Run(context.Background(), agent, messages1)
	if err != nil {
		log.Fatalf("Run failed: %v", err)
	}

	fmt.Printf("Agent response: %s\n", result.FinalOutput)
	fmt.Printf("Steps taken: %d\n", len(result.Steps))
	fmt.Println()

	// Example 2: Request a file
	fmt.Println("=== Example 2: Multimodal File Output ===")
	messages2 := []openai.ChatCompletionMessageParamUnion{
		openai.UserMessage("Create a report titled 'Q4 Summary' with content about sales performance"),
	}

	result, err = runner.Run(context.Background(), agent, messages2)
	if err != nil {
		log.Fatalf("Run failed: %v", err)
	}

	fmt.Printf("Agent response: %s\n", result.FinalOutput)
	fmt.Println()

	// Example 3: Traditional string output (backward compatibility)
	fmt.Println("=== Example 3: Traditional Text Output (Backward Compatibility) ===")
	messages3 := []openai.ChatCompletionMessageParamUnion{
		openai.UserMessage("What's the weather in San Francisco?"),
	}

	result, err = runner.Run(context.Background(), agent, messages3)
	if err != nil {
		log.Fatalf("Run failed: %v", err)
	}

	fmt.Printf("Agent response: %s\n", result.FinalOutput)
	fmt.Printf("Token usage: %d total\n", result.Usage.TotalTokens)
}
